package com.assistacrise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CriseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllPropertiesEquals(Crise expected, Crise actual) {
        assertCriseAutoGeneratedPropertiesEquals(expected, actual);
        assertCriseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAllUpdatablePropertiesEquals(Crise expected, Crise actual) {
        assertCriseUpdatableFieldsEquals(expected, actual);
        assertCriseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseAutoGeneratedPropertiesEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableFieldsEquals(Crise expected, Crise actual) {
        assertThat(actual)
            .as("Verify Crise relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFermeture()).as("check dateFermeture").isEqualTo(expected.getDateFermeture()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriseUpdatableRelationshipsEquals(Crise expected, Crise actual) {
        // empty method
    }
}
