package com.assistacrise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InformationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAllPropertiesEquals(Information expected, Information actual) {
        assertInformationAutoGeneratedPropertiesEquals(expected, actual);
        assertInformationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAllUpdatablePropertiesEquals(Information expected, Information actual) {
        assertInformationUpdatableFieldsEquals(expected, actual);
        assertInformationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationAutoGeneratedPropertiesEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationUpdatableFieldsEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information relevant properties")
            .satisfies(a -> assertThat(a.getTitre()).as("check titre").isEqualTo(expected.getTitre()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getDatePublication()).as("check datePublication").isEqualTo(expected.getDatePublication()))
            .satisfies(a -> assertThat(a.getLatitude()).as("check latitude").isEqualTo(expected.getLatitude()))
            .satisfies(a -> assertThat(a.getLongitude()).as("check longitude").isEqualTo(expected.getLongitude()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInformationUpdatableRelationshipsEquals(Information expected, Information actual) {
        assertThat(actual)
            .as("Verify Information relationships")
            .satisfies(a -> assertThat(a.getCrise()).as("check crise").isEqualTo(expected.getCrise()));
    }
}
