package com.assistacrise.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageChatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageChatAllPropertiesEquals(MessageChat expected, MessageChat actual) {
        assertMessageChatAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageChatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageChatAllUpdatablePropertiesEquals(MessageChat expected, MessageChat actual) {
        assertMessageChatUpdatableFieldsEquals(expected, actual);
        assertMessageChatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageChatAutoGeneratedPropertiesEquals(MessageChat expected, MessageChat actual) {
        assertThat(actual)
            .as("Verify MessageChat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageChatUpdatableFieldsEquals(MessageChat expected, MessageChat actual) {
        assertThat(actual)
            .as("Verify MessageChat relevant properties")
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getDateEnvoi()).as("check dateEnvoi").isEqualTo(expected.getDateEnvoi()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageChatUpdatableRelationshipsEquals(MessageChat expected, MessageChat actual) {
        assertThat(actual)
            .as("Verify MessageChat relationships")
            .satisfies(a -> assertThat(a.getDemande()).as("check demande").isEqualTo(expected.getDemande()));
    }
}
